steps:
  # Step 3: Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-app/server', '-f', 'Dockerfile', '.']
    dir: './node-sample-app'

  # Step 4: Push the backend Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-app/server']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-app' # Replace with your Cloud Run service name
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/demo-app/server'
      - '--region=us-central1' # Replace with your preferred region
      - '--platform=managed'
      - '--allow-unauthenticated' # Add this if you want the service to be publicly accessible


  
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-app/server'

options:
  logging: CLOUD_LOGGING_ONLY